---
- name: Install NFS server package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Ensure NFS share directory exists
  ansible.builtin.file:
    path: /rpi_nfs_share
    state: directory
    mode: '0777'

- name: Configure NFS exports
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /rpi_nfs_share *(rw,sync,no_subtree_check,no_root_squash)
    mode: '0644'

- name: Restart NFS service
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes

# Setup samba
# TODO: This doesn't work
- name: Install Samba
  apt:
    name:
      - samba
    state: present

- name: Ensure Samba is running
  systemd:
    name: smbd
    state: started
    enabled: yes

- name: Ensure [global] section exists
  lineinfile:
    path: /etc/samba/smb.conf
    line: "[global]"
    state: present
  notify: Restart Samba

- name: Ensure security = user is set in [global]
  lineinfile:
    path: /etc/samba/smb.conf
    insertafter: '^\[global\]'
    line: "  security = user"
    state: present

- name: Ensure passdb backend is set in [global]
  lineinfile:
    path: /etc/samba/smb.conf
    insertafter: '^\[global\]'
    line: "  passdb backend = tdbsam"
    state: present

- name: Ensure [global] section exists
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [global]
      security = user
      passdb backend = tdbsam
    insertafter: EOF
    create: yes

- name: Configure Samba share for /nfs_share
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [rpi_nfs_share]
      path = /rpi_nfs_share
      available = yes
      valid users = pi
      read only = no
      browseable = yes
      writable = yes

- name: Ensure pi user is added to Samba database
  command: "smbpasswd -a -n {{ ansible_user }}"

- name: Restart Samba to apply changes
  systemd:
    name: smbd
    state: restarted