---
- name: Install NFS server package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Ensure NFS share directory exists
  ansible.builtin.file:
    path: /rpi_nfs_share
    state: directory
    mode: '0777'

- name: Configure NFS exports
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /rpi_nfs_share *(rw,sync,no_subtree_check,no_root_squash)
    mode: '0644'

- name: Restart NFS service
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes

# Setup samba
- name: Install Samba
  apt:
    name: samba
    state: present

- name: Add Samba password for pi user
  command: "echo -e '{{ samba_password }}\n{{ samba_password }}' | smbpasswd -a pi"
  args:
    creates: "/etc/samba/smbpasswd"

- name: Ensure Samba is running
  systemd:
    name: smbd
    state: started
    enabled: yes

- name: Configure Samba share for /nfs_share
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [rpi_nfs_share]
      path = /rpi_nfs_share
      available = yes
      valid users = pi
      read only = no
      browseable = yes
      public = yes
      writable = yes
      
- name: Restart Samba to apply changes
  systemd:
    name: smbd
    state: restarted